### ISSUE TITLE
feature: responsive theme

### ISSUE THREAD

**Issue by liuly0322** [khalby786/vue-utterances#2]
I really love your work!

I'm now using it in my own blog, and I think it's a good idea to add responsive theme feature for this component

for utterances, there's a way to change theme dynamically:

```
document.querySelector("iframe")?.contentWindow?.postMessage({
  type: "set-theme",
  theme: "github-dark"  // theme you want
}, 'https://utteranc.es')
```

Maybe we can watch the theme props and dynamically refresh it? It's useful for dark mode

I'm new to Vue and not sure whether it works, but I'm willing to create a pull request if you need

Thanks!

**Comment by khalby786** [comment]
Hi @liuly0322!

Thanks a lot for the kind words, I really appreciate it!

I have updated the package with this new functionality. (v0.2.4)

Using Vue watchers to listen for the changes to the `theme` prop and then executing the snippet you provided above did the trick.

You can see an example [here](https://github.com/khalby786/vue-utterances/blob/master/dev/serve.vue).

https://github.com/khalby786/vue-utterances/commit/ceb577b55e75b226de05950079536537d66c61e9

Cheers!

**Comment by liuly0322** [comment]
@khalby786 Cool! Thanks for your work
